//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCCMaker {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCCMaker.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please either load a transcipt or press the &quot;Save &amp;&amp; Add New&quot; button first..
        /// </summary>
        internal static string edit_changeActive_transcriptNull {
            get {
                return ResourceManager.GetString("edit_changeActive_transcriptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Record failed. At least one of the timecodes are not formatted correctly. Try again..
        /// </summary>
        internal static string edit_record_fail_timecodeFormat {
            get {
                return ResourceManager.GetString("edit_record_fail_timecodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create and record failed. At least one of the timecodes are not formatted correctly..
        /// </summary>
        internal static string edit_record_fail_timecodeFormat_fromNew {
            get {
                return ResourceManager.GetString("edit_record_fail_timecodeFormat_fromNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Record failed. You must first load a caption file, transcript, or click &quot;Record &amp;&amp; Add New&quot;..
        /// </summary>
        internal static string edit_record_fail_transcriptNull {
            get {
                return ResourceManager.GetString("edit_record_fail_transcriptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recorded. Inserted new caption at current position..
        /// </summary>
        internal static string edit_record_success_addNew {
            get {
                return ResourceManager.GetString("edit_record_success_addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created new transcript and recorded given info. New caption ready..
        /// </summary>
        internal static string edit_record_success_addNew_fromNew {
            get {
                return ResourceManager.GetString("edit_record_success_addNew_fromNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recorded. Next caption ready..
        /// </summary>
        internal static string edit_record_success_continue {
            get {
                return ResourceManager.GetString("edit_record_success_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recorded. End of transcript..
        /// </summary>
        internal static string edit_record_success_end {
            get {
                return ResourceManager.GetString("edit_record_success_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove failed. Removing would create an empty transcript..
        /// </summary>
        internal static string edit_remove_fail_sizeOne {
            get {
                return ResourceManager.GetString("edit_remove_fail_sizeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove failed. No active transcipt..
        /// </summary>
        internal static string edit_remove_fail_transcriptNull {
            get {
                return ResourceManager.GetString("edit_remove_fail_transcriptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export failed. No captions TO export..
        /// </summary>
        internal static string export_fail_transcriptEmpty {
            get {
                return ResourceManager.GetString("export_fail_transcriptEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export cancelled by user..
        /// </summary>
        internal static string export_fail_userCancel {
            get {
                return ResourceManager.GetString("export_fail_userCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export to SCC successful..
        /// </summary>
        internal static string export_success {
            get {
                return ResourceManager.GetString("export_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File loaded. {0} caption{1} loaded..
        /// </summary>
        internal static string load_success {
            get {
                return ResourceManager.GetString("load_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An I/O exception occurred. The selected file may be in use by another program..
        /// </summary>
        internal static string save_fail_IO {
            get {
                return ResourceManager.GetString("save_fail_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save failed. No captions TO save..
        /// </summary>
        internal static string save_fail_transcriptEmpty {
            get {
                return ResourceManager.GetString("save_fail_transcriptEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save cancelled by user..
        /// </summary>
        internal static string save_fail_userCancel {
            get {
                return ResourceManager.GetString("save_fail_userCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save successful..
        /// </summary>
        internal static string save_success {
            get {
                return ResourceManager.GetString("save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SCCMaker v2
        ///.
        /// </summary>
        internal static string saveVersion_v2 {
            get {
                return ResourceManager.GetString("saveVersion_v2", resourceCulture);
            }
        }
    }
}
